import {
  SunDim,
  Sun,
  LayoutGrid,
  Search,
  Mic,
  Moon,
  Rewind,
  Play,
  FastForward,
  VolumeX,
  Volume1,
  Volume2,
  Hash,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";

// Layout maps for different keyboard layouts
export const layoutMaps = {
  qwerty: {},
  azerty: {
    KeyQ: "A",
    KeyW: "Z",
    KeyA: "Q",
    KeyZ: "W",
    KeyM: ";",
    Semicolon: "M",
    Minus: ")",
    Equal: "=",
    BracketLeft: "^",
    BracketRight: "$",
    Backslash: "£",
    Quote: "ù",
    Slash: "!",
  },
  dvorak: {
    KeyQ: "'",
    KeyW: ",",
    KeyE: ".",
    KeyR: "P",
    KeyT: "Y",
    KeyY: "F",
    KeyU: "G",
    KeyI: "C",
    KeyO: "R",
    KeyP: "L",
    KeyA: "A",
    KeyS: "O",
    KeyD: "E",
    KeyF: "U",
    KeyG: "I",
    KeyH: "D",
    KeyJ: "H",
    KeyK: "T",
    KeyL: "N",
    KeyZ: ";",
    KeyX: "Q",
    KeyC: "J",
    KeyV: "K",
    KeyB: "X",
    KeyN: "B",
    KeyM: "M",
    Minus: "[",
    Equal: "]",
    BracketLeft: "/",
    BracketRight: "=",
    Backslash: "\\",
    Semicolon: "S",
    Quote: "-",
    Comma: "W",
    Period: "V",
    Slash: "Z",
  },
};

// Base key rows (QWERTY) with the requested layout changes
export const baseRows = [
  // Row 0: Esc, F1–F12, Print Screen (replaces Delete), Delete (no icon)
  [
    {
      label: "esc",
      code: "Escape",
      width: "45px",
      color: "bright-red",
      align: "tl",
    },
    {
      label: "F1",
      icon: <SunDim size={12} />,
      code: "F1",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F2",
      icon: <Sun size={12} />,
      code: "F2",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F3",
      icon: <LayoutGrid size={12} />,
      code: "F3",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F4",
      icon: <Search size={11} />,
      code: "F4",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F5",
      icon: <Mic size={11} />,
      code: "F5",
      width: "40px",
      color: "dark-red",
      align: "c",
    },
    {
      label: "F6",
      icon: <Moon size={11} />,
      code: "F6",
      width: "40px",
      color: "dark-red",
      align: "c",
    },
    {
      label: "F7",
      icon: <Rewind size={11} />,
      code: "F7",
      width: "40px",
      color: "dark-red",
      align: "c",
    },
    {
      label: "F8",
      icon: <Play size={11} />,
      code: "F8",
      width: "40px",
      color: "dark-red",
      align: "c",
    },
    {
      label: "F9",
      icon: <FastForward size={11} />,
      code: "F9",
      width: "40px",
      color: "dark-red",
      align: "c",
    },
    {
      label: "F10",
      icon: <VolumeX size={11} />,
      code: "F10",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F11",
      icon: <Volume1 size={11} />,
      code: "F11",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "F12",
      icon: <Volume2 size={11} />,
      code: "F12",
      width: "40px",
      color: "white",
      align: "c",
    },
    // F13 becomes Insert (no icon)
    {
      label: "ins",
      code: "Insert",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
    // Delete becomes Print Screen
    {
      label: "prt sc",
      code: "PrintScreen",
      width: "45px",
      color: "dark-red",
      align: "tl",
    },
    // Far right: Delete (no icon)
    {
      label: "del",
      code: "Delete",
      width: "45px",
      color: "dark-red",
      align: "tl",
    },
  ],
  // Row 1: numbers, backspace, and navigation cluster: Home (was PageUp)
  [
    {
      label: "~\n`",
      code: "Backquote",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "!\n1",
      code: "Digit1",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "@\n2",
      code: "Digit2",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "#\n3",
      code: "Digit3",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "$\n4",
      code: "Digit4",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "%\n5",
      code: "Digit5",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "^\n6",
      code: "Digit6",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "&\n7",
      code: "Digit7",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "*\n8",
      code: "Digit8",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "(\n9",
      code: "Digit9",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: ")\n0",
      code: "Digit0",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "_\n-",
      code: "Minus",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "+\n=",
      code: "Equal",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "backspace\n←",
      code: "Backspace",
      width: "96px",
      color: "dark-red",
      align: "tl",
    },
    // Home (was PageUp) – unchanged
    {
      label: "home",
      code: "Home",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
  ],
  // Row 2: tab, letters, brackets, backslash, and PageUp (was PageDown) – now "pg up"
  [
    {
      label: "tab",
      code: "Tab",
      width: "68px",
      color: "dark-red",
      align: "tl",
    },
    { label: "Q", code: "KeyQ", width: "40px", color: "white", align: "tl" },
    { label: "W", code: "KeyW", width: "40px", color: "white", align: "tl" },
    { label: "E", code: "KeyE", width: "40px", color: "white", align: "tl" },
    { label: "R", code: "KeyR", width: "40px", color: "white", align: "tl" },
    { label: "T", code: "KeyT", width: "40px", color: "white", align: "tl" },
    { label: "Y", code: "KeyY", width: "40px", color: "white", align: "tl" },
    { label: "U", code: "KeyU", width: "40px", color: "white", align: "tl" },
    { label: "I", code: "KeyI", width: "40px", color: "white", align: "tl" },
    { label: "O", code: "KeyO", width: "40px", color: "white", align: "tl" },
    { label: "P", code: "KeyP", width: "40px", color: "white", align: "tl" },
    {
      label: "{\n[",
      code: "BracketLeft",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "}\n]",
      code: "BracketRight",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "|\n\\",
      code: "Backslash",
      width: "68px",
      color: "white",
      align: "tl",
    },
    // PageUp (was PageDown) – now "pg up"
    {
      label: "pg up",
      code: "PageUp",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
  ],
  // Row 3: caps, letters, enter, and PageDown (was Home) – now "pg dn"
  [
    {
      label: "caps lock",
      code: "CapsLock",
      width: "83px",
      color: "dark-red",
      align: "tl",
    },
    { label: "A", code: "KeyA", width: "40px", color: "white", align: "tl" },
    { label: "S", code: "KeyS", width: "40px", color: "white", align: "tl" },
    { label: "D", code: "KeyD", width: "40px", color: "white", align: "tl" },
    { label: "F", code: "KeyF", width: "40px", color: "white", align: "tl" },
    { label: "G", code: "KeyG", width: "40px", color: "white", align: "tl" },
    { label: "H", code: "KeyH", width: "40px", color: "white", align: "tl" },
    { label: "J", code: "KeyJ", width: "40px", color: "white", align: "tl" },
    { label: "K", code: "KeyK", width: "40px", color: "white", align: "tl" },
    { label: "L", code: "KeyL", width: "40px", color: "white", align: "tl" },
    {
      label: ":\n;",
      code: "Semicolon",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "\"\n'",
      code: "Quote",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "return",
      code: "Enter",
      width: "95px",
      color: "bright-red",
      align: "tl",
    },
    // PageDown (was Home) – now "pg dn"
    {
      label: "pg dn",
      code: "PageDown",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
  ],
  // Row 4: shift, letters, shift, arrow up, End (unchanged)
  [
    {
      label: "shift",
      code: "ShiftLeft",
      width: "100px",
      color: "dark-red",
      align: "tl",
    },
    { label: "Z", code: "KeyZ", width: "40px", color: "white", align: "tl" },
    { label: "X", code: "KeyX", width: "40px", color: "white", align: "tl" },
    { label: "C", code: "KeyC", width: "40px", color: "white", align: "tl" },
    { label: "V", code: "KeyV", width: "40px", color: "white", align: "tl" },
    { label: "B", code: "KeyB", width: "40px", color: "white", align: "tl" },
    { label: "N", code: "KeyN", width: "40px", color: "white", align: "tl" },
    { label: "M", code: "KeyM", width: "40px", color: "white", align: "tl" },
    {
      label: "<\n,",
      code: "Comma",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: ">\n.",
      code: "Period",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "?\n/",
      code: "Slash",
      width: "40px",
      color: "white",
      align: "tl",
    },
    {
      label: "shift",
      code: "ShiftRight",
      width: "78px",
      color: "dark-red",
      align: "tl",
    },
    {
      label: "",
      icon: <ChevronUp size={16} />,
      code: "ArrowUp",
      width: "40px",
      color: "white",
      align: "c",
    },
    // End (unchanged)
    {
      label: "end",
      code: "End",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
  ],
  // Row 5: modifiers, space, arrows
  [
    {
      label: "ctrl",
      code: "ControlLeft",
      width: "51px",
      color: "dark-red",
      align: "tl",
    },
    {
      label: "option",
      code: "AltLeft",
      width: "51px",
      color: "dark-red",
      align: "tl",
    },
    {
      label: "⌘",
      code: "MetaLeft",
      width: "51px",
      color: "dark-red",
      align: "tl",
    },
    { label: "", code: "Space", width: "271px", color: "white", align: "c" },
    {
      label: "⌘",
      code: "MetaRight",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
    { label: "fn", code: "Fn", width: "40px", color: "dark-red", align: "tl" },
    {
      label: "ctrl",
      code: "ControlRight",
      width: "40px",
      color: "dark-red",
      align: "tl",
    },
    {
      label: "",
      icon: <ChevronLeft size={16} />,
      code: "ArrowLeft",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "",
      icon: <ChevronDown size={16} />,
      code: "ArrowDown",
      width: "40px",
      color: "white",
      align: "c",
    },
    {
      label: "",
      icon: <ChevronRight size={16} />,
      code: "ArrowRight",
      width: "40px",
      color: "white",
      align: "c",
    },
  ],
];
